<a href="https://colab.research.google.com/github/doshimihir07/python_colab/blob/main/Hands_on_Notebook_Pandas_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# importing the libraries
import numpy as np
import pandas as pd

In [ ]:
np.random.rand(3,2)

array([[0.76098865, 0.82210526],
       [0.65939536, 0.17785967],
       [0.48054594, 0.26317637]])

### 2.6 Pandas -  Series and DataFrames

**Pandas Series**
* Pandas Series is a one-dimensional labeled array/list capable of holding data of any type (integer, string, float, python objects, etc.).
* The labels are collectively called index.
* Pandas Series can be thought as a single column of an excel spreadsheet and each entry in a series corresponds to an individual row in the spreadsheet.

In [ ]:
# creating a list of price of different medicines
med_price_list = [55,25,75,40,90]

# converting the med_price_list to an array
med_price_arr = np.array(med_price_list)

# converting the list and array into a Pandas Series object
series_list = pd.Series(med_price_list)
series_arr = pd.Series(med_price_arr)

# printing the converted series object
print(series_list)
print(series_arr)

0    55
1    25
2    75
3    40
4    90
dtype: int64
0    55
1    25
2    75
3    40
4    90
dtype: int64


* We can see that the list and array have been converted to a Pandas Series object.
* We also see that the series has automatically got index labels. Let's see how these can be modified.

In [ ]:
import pandas as pd

bucket=[3.14,'pi',2.718]

series=pd.Series(bucket)


In [ ]:
import pandas as pd

items={'col1':[1,2,3],'col2':[3,4,5]}
df_from_dict=pd.DataFrame(items)
type(df_from_dict)

pandas.core.frame.DataFrame

In [ ]:
import pandas as pd

df=pd.read_csv('data.csv',delimiter=';')


In [ ]:
# prompt: Step 1: Import Libraries
# import pandas as pd
# Step 2: Read Dataset
# Read the dataset from 'data.csv' into a variable named  df
# Step 3: Define the boolean expression
# Write the boolean expression to include only the rows where the age is greater than 23 and assign it to a variable named age_filtered
# Step 4: Filtering records
# Apply the boolean expression age_filtered on the df and assign the result to a variable named result

# Assuming 'data.csv' is in the current working directory.
# If not, provide the correct path.

import pandas as pd

df = pd.read_csv('data.csv', delimiter=';')

age_filtered = df['age'] > 23  # Assuming 'age' is a column in your DataFrame

result = df[age_filtered]

In [ ]:
series_arr[1:6]

1    25
2    75
3    40
4    90
dtype: int64

In [ ]:
# changing the index of a series
med_price_list_labeled = pd.Series(med_price_list, index = ['Omeprazole','Azithromycin','Metformin','Ibuprofen','Cetirizine'])
print(med_price_list_labeled)

Omeprazole      55
Azithromycin    25
Metformin       75
Ibuprofen       40
Cetirizine      90
dtype: int64


**Performing mathematical operations on Pandas Series**

* The price of each medicine was increased by $2.5. Let's add this to the existing price.

In [ ]:
# adding 2.5 to existing prices
med_price_list_labeled_updated = med_price_list_labeled + 2.5
med_price_list_labeled_updated

Omeprazole      57.5
Azithromycin    27.5
Metformin       77.5
Ibuprofen       42.5
Cetirizine      92.5
dtype: float64

* A new price list was released by vendors for each medicine. Let's find the difference between new price and the old price

In [ ]:
new_price_list = [77, 45.5, 100, 50, 80]
new_price_list_labeled = pd.Series(new_price_list, index = ['Omeprazole','Azithromycin','Metformin','Ibuprofen','Cetirizine'])
print(new_price_list_labeled)

Omeprazole       77.0
Azithromycin     45.5
Metformin       100.0
Ibuprofen        50.0
Cetirizine       80.0
dtype: float64


In [ ]:
print('Difference between new price and old price - ')
(new_price_list_labeled - med_price_list_labeled_updated)

Difference between new price and old price - 


Omeprazole      19.5
Azithromycin    18.0
Metformin       22.5
Ibuprofen        7.5
Cetirizine     -12.5
dtype: float64

**Pandas DataFrame**

Pandas DataFrame is a two-dimensional tabular data structure with labeled axes (rows and columns).

**Creating a Pandas DataFrame using a list**

In [ ]:
student = ['Mary', 'Peter', 'Susan', 'Toby', 'Vishal']
df1 = pd.DataFrame(student,columns=['Student'])
df1

Student
0    Mary
1   Peter
2   Susan
3    Toby
4  Vishal

**Creating a Pandas DataFrame using a dictionary**

In [ ]:
# defining another list
grades = ['B-','A+','A-', 'B+', 'C']

# creating the dataframe using a dictionary
df2 = pd.DataFrame({'Student':student,'Grade':grades})
df2

Student Grade
0    Mary    B-
1   Peter    A+
2   Susan    A-
3    Toby    B+
4  Vishal     C

**Creating a Pandas DataFrame using Series**

The data for total energy consumption for the U.S. was collected from 2012 - 2018. Let's see how this data can be presented in form of data frame.

In [ ]:
year = pd.Series([2012,2013,2014,2015,2016,2017,2018])
energy_consumption = pd.Series([2152,2196,2217,2194,2172,2180,2258])

df3 = pd.DataFrame({'Year':year,'Energy_Consumption(Mtoe)':energy_consumption})
df3

Year  Energy_Consumption(Mtoe)
0  2012                      2152
1  2013                      2196
2  2014                      2217
3  2015                      2194
4  2016                      2172
5  2017                      2180
6  2018                      2258

**Creating a Pandas DataFrame using random values**

For encryption purposes a web browser company wants to generate random values which have mean equal to 0 and variance equal to 1. They want 5 randomly generated numbers in 2 different trials.

In [ ]:
# we can create a new dataframe using random values
df4 = pd.DataFrame(np.random.randn(5,2),columns = ['Trial 1', 'Trial 2'])
df4

Trial 1   Trial 2
0 -0.809024  0.936279
1  1.074397  0.797168
2 -1.484739 -0.073341
3 -0.063956 -0.233958
4 -1.354096 -0.406139

### 2.7 Pandas - Accessing and Modifying

**Accessing Series**

The revenue (in billion dollars) of different telecommunication operators in U.S. was collected for the year of 2020. The following lists consist of the names of the telecommunication operators and their respective revenue (in billion dollars).

In [ ]:
operators = ['AT&T', 'Verizon', 'T-Mobile US', 'US Cellular']
revenue = [171.76, 128.29, 68.4, 4.04]

#creating a Series from lists
telecom = pd.Series(revenue, index=operators)
telecom

AT&T           171.76
Verizon        128.29
T-Mobile US     68.40
US Cellular      4.04
dtype: float64

**Accessing Pandas Series using its index**

In [ ]:
# accessing the first element of series
telecom[0]

<ipython-input-15-98b33744936b>:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  telecom[0]


171.76

In [ ]:
telecom.iloc[0]

171.76

In [ ]:
#  accessing firt 3 elements of a series
telecom[:3]

AT&T           171.76
Verizon        128.29
T-Mobile US     68.40
dtype: float64

In [ ]:
# accessing the last two elements of a series
telecom[-2:]

T-Mobile US    68.40
US Cellular     4.04
dtype: float64

In [ ]:
# accessing multiple elements of a series
telecom[[0,2,3]]

<ipython-input-19-55a626608097>:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  telecom[[0,2,3]]


AT&T           171.76
T-Mobile US     68.40
US Cellular      4.04
dtype: float64

**Accessing Pandas Series using its labeled index**

In [ ]:
# accessing the revenue of AT&T
telecom['AT&T']

171.76

In [ ]:
#  accessing firt 3 revenues of operators in the series
# Important to note that when using numbers as indexing the data shown is till before the end mentioned.
# But when using string index the end mentioned is included in the output
telecom[:'T-Mobile US']


AT&T           171.76
Verizon        128.29
T-Mobile US     68.40
dtype: float64

In [ ]:
# accessing multiple values
telecom[['AT&T','US Cellular','Verizon']]

AT&T           171.76
US Cellular      4.04
Verizon        128.29
dtype: float64

**Accessing DataFrames**

The data of the customers visiting 24/7 Stores from different locations was collected. The data includes Customer ID, location of store, gender of the customer,  type of product purchased, quantity of products purchased, total bill amount. Let's create the dataset and see how to access different entries of it.

In [ ]:
# creating the dataframe using dictionary
store_data = pd.DataFrame({'CustomerID': ['CustID00','CustID01','CustID02','CustID03','CustID04']
                           ,'location': ['Chicago', 'Boston', 'Seattle', 'San Francisco', 'Austin']
                           ,'gender': ['M','M','F','M','F']
                           ,'type': ['Electronics','Food&Beverages','Food&Beverages','Medicine','Beauty']
                           ,'quantity':[1,3,4,2,1],'total_bill':[100,75,125,50,80]})
store_data

CustomerID       location gender            type  quantity  total_bill
0   CustID00        Chicago      M     Electronics         1         100
1   CustID01         Boston      M  Food&Beverages         3          75
2   CustID02        Seattle      F  Food&Beverages         4         125
3   CustID03  San Francisco      M        Medicine         2          50
4   CustID04         Austin      F          Beauty         1          80

In [ ]:
# accessing first row of the dataframe
store_data[0:1]

CustomerID location gender         type  quantity  total_bill
0   CustID00  Chicago      M  Electronics         1         100

In [ ]:
# accessing first column of the dataframe
store_data['location']

0          Chicago
1           Boston
2          Seattle
3    San Francisco
4           Austin
Name: location, dtype: object

In [ ]:
# accessing rows with the step size of 2
store_data[::2]

CustomerID location gender            type  quantity  total_bill
0   CustID00  Chicago      M     Electronics         1         100
2   CustID02  Seattle      F  Food&Beverages         4         125
4   CustID04   Austin      F          Beauty         1          80

In [ ]:
# accessing the rows in reverse
store_data[::-2]

CustomerID location gender            type  quantity  total_bill
4   CustID04   Austin      F          Beauty         1          80
2   CustID02  Seattle      F  Food&Beverages         4         125
0   CustID00  Chicago      M     Electronics         1         100

**Using loc and iloc method**

**loc method**

* loc is a  method to access rows and columns on pandas objects. When using the loc method on a dataframe, we specify which rows and which columns we want by using the following format:

  * **dataframe.loc[row selection, column selection]**

* DataFrame.loc[] method is a method that takes **only index labels** and returns row or dataframe if the index label exists in the data frame.

In [ ]:
# accessing first index value using loc method (indexing starts from 0 in python)
store_data.loc[1]

CustomerID          CustID01
location              Boston
gender                     M
type          Food&Beverages
quantity                   3
total_bill                75
Name: 1, dtype: object

**Accessing selected rows and columns using loc method**

In [ ]:
# accessing 1st and 4th index values along with location and type columns
store_data.loc[[1,4],['location','type']]

location            type
1   Boston  Food&Beverages
4   Austin          Beauty

**iloc method**

* The iloc indexer for Pandas Dataframe is used for **integer location-based** indexing/selection by position. When using the loc method on a dataframe, we specify which rows and which columns we want by using the following format:

  * **dataframe.iloc[row selection, column selection]**



In [ ]:
# accessing selected rows and columns using iloc method
store_data.iloc[[1,4],[0,2]]

CustomerID gender
1   CustID01      M
4   CustID04      F

**Difference between loc and iloc indexing methods**

* loc is label-based, which means that you have to specify rows and columns based on their row and column labels.
* iloc is integer position-based, so you have to specify rows and columns by their integer position values (0-based integer position).


If we use labels instead of index values in .iloc it will throw an error.

In [ ]:
# accessing selected rows and columns using iloc method
store_data.iloc[[1,4],['location','type']]

IndexError: .iloc requires numeric indexers, got ['location' 'type']

* As expected, .iloc has given error on using 'labels'.

We can modify entries of a dataframe using loc or iloc too

In [ ]:
print(store_data.loc[4,'type'])
store_data.loc[4,'type'] = 'Electronics'

Beauty


In [ ]:
store_data

CustomerID       location gender            type  quantity  total_bill
0   CustID00        Chicago      M     Electronics         1         100
1   CustID01         Boston      M  Food&Beverages         3          75
2   CustID02        Seattle      F  Food&Beverages         4         125
3   CustID03  San Francisco      M        Medicine         2          50
4   CustID04         Austin      F     Electronics         1          80

In [ ]:
store_data.iloc[4,3] = 'Beauty'
store_data

CustomerID       location gender            type  quantity  total_bill
0   CustID00        Chicago      M     Electronics         1         100
1   CustID01         Boston      M  Food&Beverages         3          75
2   CustID02        Seattle      F  Food&Beverages         4         125
3   CustID03  San Francisco      M        Medicine         2          50
4   CustID04         Austin      F          Beauty         1          80

**Condition based indexing**

In [ ]:
store_data['quantity']>1

0    False
1     True
2     True
3     True
4    False
Name: quantity, dtype: bool

* Wherever the condition of greater than 1 is satisfied in quantity column, 'True' is returned. Let's retrieve the original values wherever the condition is satisfied.

In [ ]:
store_data.loc[store_data['quantity']>1]

CustomerID       location gender            type  quantity  total_bill
1   CustID01         Boston      M  Food&Beverages         3          75
2   CustID02        Seattle      F  Food&Beverages         4         125
3   CustID03  San Francisco      M        Medicine         2          50

* Wherever the condition is satisfied we get the original values, and wherever the condition is not satisfied we do not get those records in the output.

**Column addition and removal from a Pandas DataFrame**

**Adding a new column in a DataFrame**

In [ ]:
store_data

CustomerID       location gender            type  quantity  total_bill
0   CustID00        Chicago      M     Electronics         1         100
1   CustID01         Boston      M  Food&Beverages         3          75
2   CustID02        Seattle      F  Food&Beverages         4         125
3   CustID03  San Francisco      M        Medicine         2          50
4   CustID04         Austin      F          Beauty         1          80

In [ ]:
# adding a new column in data frame store_data which is a rating (out of 5) given by customer based on their shopping experience
store_data['rating'] = [2,5,3,4,4]
store_data

CustomerID       location gender            type  quantity  total_bill  \
0   CustID00        Chicago      M     Electronics         1         100   
1   CustID01         Boston      M  Food&Beverages         3          75   
2   CustID02        Seattle      F  Food&Beverages         4         125   
3   CustID03  San Francisco      M        Medicine         2          50   
4   CustID04         Austin      F          Beauty         1          80   

   rating  
0       2  
1       5  
2       3  
3       4  
4       4

**Removing a column from a DataFrame**

* The CustomerID column is a unique identifier of each customer. This unique identifier will not help 24/7 Stores in getting useful insights about their customers. So, they have decided to remove this column from the data frame.

In [ ]:
store_data.drop('CustomerID',axis=1)

location gender            type  quantity  total_bill  rating
0        Chicago      M     Electronics         1         100       2
1         Boston      M  Food&Beverages         3          75       5
2        Seattle      F  Food&Beverages         4         125       3
3  San Francisco      M        Medicine         2          50       4
4         Austin      F          Beauty         1          80       4

* We sucessfully removed the 'CustomerID' from dataframe. But this change is not permanent in the dataframe, let's have a look at the store_data again.

In [ ]:
store_data

CustomerID       location gender            type  quantity  total_bill  \
0   CustID00        Chicago      M     Electronics         1         100   
1   CustID01         Boston      M  Food&Beverages         3          75   
2   CustID02        Seattle      F  Food&Beverages         4         125   
3   CustID03  San Francisco      M        Medicine         2          50   
4   CustID04         Austin      F          Beauty         1          80   

   rating  
0       2  
1       5  
2       3  
3       4  
4       4

* We see that store_data still has column 'CustomerID' in it.
* To make permanent changes to a dataframe there are two methods will have to use a parameter `inplace` and set its value to `True`.

In [ ]:
store_data.drop('CustomerID',axis=1,inplace=True)
store_data

location gender            type  quantity  total_bill  rating
0        Chicago      M     Electronics         1         100       2
1         Boston      M  Food&Beverages         3          75       5
2        Seattle      F  Food&Beverages         4         125       3
3  San Francisco      M        Medicine         2          50       4
4         Austin      F          Beauty         1          80       4

* Now the column has been permanently removed from the dataframe.

In [ ]:
# we can also remove multiple columns simultaneously
# it is always a good idea to store the new/updated data frames in new variables to avoid changes to the existing data frame

# creating a copy of the existing data frame
new_store_data = store_data.copy()
store_data

location gender            type  quantity  total_bill  rating
0        Chicago      M     Electronics         1         100       2
1         Boston      M  Food&Beverages         3          75       5
2        Seattle      F  Food&Beverages         4         125       3
3  San Francisco      M        Medicine         2          50       4
4         Austin      F          Beauty         1          80       4

In [ ]:
# dropping location and rating columns simultaneously
new_store_data.drop(['location','rating'],axis=1,inplace=True)
new_store_data

gender            type  quantity  total_bill
0      M     Electronics         1         100
1      M  Food&Beverages         3          75
2      F  Food&Beverages         4         125
3      M        Medicine         2          50
4      F          Beauty         1          80

In [ ]:
# lets check if store_data was impacted
store_data

location gender            type  quantity  total_bill  rating
0        Chicago      M     Electronics         1         100       2
1         Boston      M  Food&Beverages         3          75       5
2        Seattle      F  Food&Beverages         4         125       3
3  San Francisco      M        Medicine         2          50       4
4         Austin      F          Beauty         1          80       4

* There were no changes to data frame store_data.

* Deep copy stores copies of the object’s value.
* Shallow Copy stores the references of objects to the original memory address.

**Removing rows from a dataframe**

In [ ]:
store_data.drop(1,axis=0)

location gender            type  quantity  total_bill  rating
0        Chicago      M     Electronics         1         100       2
2        Seattle      F  Food&Beverages         4         125       3
3  San Francisco      M        Medicine         2          50       4
4         Austin      F          Beauty         1          80       4

In [ ]:
store_data

location gender            type  quantity  total_bill  rating
0        Chicago      M     Electronics         1         100       2
1         Boston      M  Food&Beverages         3          75       5
2        Seattle      F  Food&Beverages         4         125       3
3  San Francisco      M        Medicine         2          50       4
4         Austin      F          Beauty         1          80       4

* Notice that we used **`axis=0`** to drop a row from a data frame, while we were using **`axis=1`** for dropping a column from the data frame.
* Also, to make permanent changes to the data frame we will have to use `inplace=True` parameter.
* We also see that the index are not correct now as first row has been removed. So, we will have to reset the index of the data frame. Let's see how this can be done.

In [ ]:
# creating a new dataframe
store_data_new  = store_data.drop(1,axis=0)
store_data_new

location gender            type  quantity  total_bill  rating
0        Chicago      M     Electronics         1         100       2
2        Seattle      F  Food&Beverages         4         125       3
3  San Francisco      M        Medicine         2          50       4
4         Austin      F          Beauty         1          80       4

In [ ]:
# resetting the index of data frame
store_data_new.reset_index()

index       location gender            type  quantity  total_bill  rating
0      0        Chicago      M     Electronics         1         100       2
1      2        Seattle      F  Food&Beverages         4         125       3
2      3  San Francisco      M        Medicine         2          50       4
3      4         Austin      F          Beauty         1          80       4

* We see that the index of the data frame is now resetted but the index has become a column in the data frame. We do not need the index to become a column so we can simply set the parameter **`drop=True`** in reset_index() function.

In [ ]:
# setting inplace = True to make the changes permanent
store_data_new.reset_index(drop=True,inplace=True)
store_data_new

location gender            type  quantity  total_bill  rating
0        Chicago      M     Electronics         1         100       2
1        Seattle      F  Food&Beverages         4         125       3
2  San Francisco      M        Medicine         2          50       4
3         Austin      F          Beauty         1          80       4

### 2.8 Pandas - Combining DataFrames

We will examine 3 methods for combining dataframes

1. concat
2. join
3. merge

In [ ]:
data_cust = pd.DataFrame({"customerID":['101','102','103','104'],
                        'category': ['Medium','Medium','High','Low'],
                        'first_visit': ['yes','no','yes','yes'],
                        'sales': [123,52,214,663]},index=[0,1,2,3])

data_cust_new = pd.DataFrame({"customerID":['101','103','104','105'],
                    'distance': [12,9,44,21],
                    'sales': [123,214,663,331]},index=[4,5,6,7])

In [ ]:
data_cust

customerID category first_visit  sales
0        101   Medium         yes    123
1        102   Medium          no     52
2        103     High         yes    214
3        104      Low         yes    663

In [ ]:
data_cust_new

customerID  distance  sales
4        101        12    123
5        103         9    214
6        104        44    663
7        105        21    331

In [ ]:
pd.concat([data_cust,data_cust_new],axis=0)

customerID category first_visit  sales  distance
0        101   Medium         yes    123       NaN
1        102   Medium          no     52       NaN
2        103     High         yes    214       NaN
3        104      Low         yes    663       NaN
4        101      NaN         NaN    123      12.0
5        103      NaN         NaN    214       9.0
6        104      NaN         NaN    663      44.0
7        105      NaN         NaN    331      21.0

In [ ]:
pd.concat([data_cust,data_cust_new],axis=1)

customerID category first_visit  sales customerID  distance  sales
0        101   Medium         yes  123.0        NaN       NaN    NaN
1        102   Medium          no   52.0        NaN       NaN    NaN
2        103     High         yes  214.0        NaN       NaN    NaN
3        104      Low         yes  663.0        NaN       NaN    NaN
4        NaN      NaN         NaN    NaN        101      12.0  123.0
5        NaN      NaN         NaN    NaN        103       9.0  214.0
6        NaN      NaN         NaN    NaN        104      44.0  663.0
7        NaN      NaN         NaN    NaN        105      21.0  331.0

**Merge and Join**

* Merge combines dataframes using a column's values to identify common entries

* Join combines dataframes using the index to identify common entries

In [ ]:
pd.merge(data_cust,data_cust_new,how='outer',on='customerID') # outer merge is union of on

customerID category first_visit  sales_x  distance  sales_y
0        101   Medium         yes    123.0      12.0    123.0
1        102   Medium          no     52.0       NaN      NaN
2        103     High         yes    214.0       9.0    214.0
3        104      Low         yes    663.0      44.0    663.0
4        105      NaN         NaN      NaN      21.0    331.0

In [ ]:
pd.merge(data_cust,data_cust_new,how='inner',on='customerID') # inner merge is intersection of on

customerID category first_visit  sales_x  distance  sales_y
0        101   Medium         yes      123        12      123
1        103     High         yes      214         9      214
2        104      Low         yes      663        44      663

In [ ]:
pd.merge(data_cust,data_cust_new,how='right',on='customerID')

customerID category first_visit  sales_x  distance  sales_y
0        101   Medium         yes    123.0        12      123
1        103     High         yes    214.0         9      214
2        104      Low         yes    663.0        44      663
3        105      NaN         NaN      NaN        21      331

In [ ]:
data_quarters = pd.DataFrame({'Q1': [101,102,103],
                              'Q2': [201,202,203]},
                               index=['I0','I1','I2'])

data_quarters_new = pd.DataFrame({'Q3': [301,302,303],
                                  'Q4': [401,402,403]},
                               index=['I0','I2','I3'])

In [ ]:
data_quarters

Q1   Q2
I0  101  201
I1  102  202
I2  103  203

In [ ]:
data_quarters_new

Q3   Q4
I0  301  401
I2  302  402
I3  303  403

* `join` behaves just like merge,  except instead of using the values of one of the columns to combine data frames, it uses the index labels

In [ ]:
data_quarters.join(data_quarters_new,how='right') # outer, inner, left, and right work the same as merge

Q1     Q2   Q3   Q4
I0  101.0  201.0  301  401
I2  103.0  203.0  302  402
I3    NaN    NaN  303  403

### 2.9 Pandas - Saving and Loading DataFrames

**Note**

In real-life scenario, we deal with much larger datasets that have thousands of rows and multiple columns. It will not be feasible for us to create datasets using multiple lists, especially if the number of columns and rows increases.

So, it is clear we need a more efficient way of handling the data simultaneously at the columns and row levels. In Python, we can import dataset from our local system, from links, or from databases and work on them directly instead of creating our own dataset.

**Loading a CSV file in Python**

**For Jupyter Notebook**
* When the data file and jupyter notebook are in the same folder.

In [ ]:
# Using pd.read_csv() function will work without any path if the notebook and dataset are in the folder

# data = pd.read_csv('StockData.csv')

**For Google Colab with Google Drive**

First, we have to give google colab access to our google drive:

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


Once we have access we can load files from google drive using read_csv() function.

In [ ]:
path="/content/drive/MyDrive/Python Course/StockData.csv"
data=pd.read_csv(path)

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Python Course/StockData.csv'

In [ ]:
# head() function helps us to see the first 5 rows of the data
data.head()

NameError: name 'data' is not defined

**Loading an excel file in Python**

In [ ]:
path_excel="/content/drive/MyDrive/Python Course/StockData.xlsx"
data_excel = pd.read_excel(path_excel)

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Python Course/StockData.xlsx'

In [ ]:
data_excel.head()

NameError: name 'data_excel' is not defined

**Saving a dataset in Python**

**Saving the dataset as a csv file**

To save a dataset as .csv file the syntax used is -

**data.to_csv('name of the file.csv', index=False)**

In [ ]:
data.to_csv('/content/drive/MyDrive/Python Course/Saved_StockData.csv',index=False)

* In jupyter notebook, the dataset will be saved in the folder where the jupyter notebook is located.
* We can also save the dataset to a desired folder by providing the path/location of the folder.

**Saving the dataset as an excel spreadsheet**

To save a dataset as .xlsx file the syntax used is -

**data.to_excel('name of the file.xlsx',index=False)**

In [ ]:
data.to_excel('/content/drive/MyDrive/Python Course/Saved_StockData.xlsx',index=False)

### 2.10 Pandas - Functions

**head() - to check the first 5 rows of the dataset**

In [ ]:
data.head()

NameError: name 'data' is not defined

**tail() - to check the last 5 rows of the dataset**

In [ ]:
data.tail()

**shape - to check the number of rows and columns in the dataset**

In [ ]:
data.shape

* The dataset has 5036 rows and 3 columns.

**info() - to check the data type of the columns**

In [ ]:
data.info()

* The price column is numeric in nature while the stock and date columns are of object types.

**min() - to check the minimum value of a numeric column**

In [ ]:
data['price'].min()

**max() - to check the maximum value of a numeric column**

In [ ]:
data['price'].max()

**unique() - to check the number of unique values that are present in a column**

In [ ]:
data['stock'].unique()



```
# This is formatted as code
```

**value_counts() - to check the number of values that each unique quantity has in a column**

In [ ]:
data['stock'].value_counts()

**value_counts(normalize=True) - using the `normalize` parameter and initializing it to True will return the relative frequencies of the unique values.**

In [ ]:
data['stock'].value_counts(normalize=True)

**Statistical Functions**

**mean() - to check the mean (average) value of the column**

In [ ]:
data['price'].mean()

**median() - to check the median value of the column**

In [ ]:
data['price'].median()

**mode() - to check the mode value of the column**

In [ ]:
data['stock'].mode()

**To access a particular mode when the dataset has more than 1 mode**

In [ ]:
#to access the first mode
data['price'].mode()[0]

**Group By function**
* Pandas dataframe.groupby() function is used to split the data into groups based on some criteria.

In [ ]:
data.groupby(['stock'])['price'].mean()

* Here the groupby function is used to split the data into the 4 stocks that are present in the dataset and then the mean price of each of the 4 stock is calculated.

In [ ]:
# similarly we can get the median price of each stock
data.groupby(['stock'])['price'].median()

* Here the groupby function is used to split the data into the 4 stocks that are present in the dataset and then the median price of each of the 4 stock is calculated.

**Let's create a function to increase the price of the stock by 10%**

In [ ]:
def profit(s):
    return s + s*0.10 # increase of 10%

**The Pandas apply() function lets you to manipulate columns and rows in a DataFrame.**

In [ ]:
data['price'].apply(profit)

* We can now add this updated values in the dataset.

In [ ]:
data['new_price'] =data['price'].apply(profit)
data.head()

**Pandas sort_values() function sorts a data frame in ascending or descending order of passed column.**

In [ ]:
data.sort_values(by='new_price',ascending=False) # by default ascending is set to True

### 2.11 Pandas - Date-time Functions

In [ ]:
# reading the StockData
path="/content/drive/MyDrive/Python Course/StockData.csv"
data=pd.read_csv(path)

In [ ]:
# checking the first 5 rows of the dataset
data.head()

In [ ]:
# checking the data type of columns in the dataset
data.info()

* We observe that the date column is of object type whereas it should be of date time data type.

In [ ]:
# converting the date column to datetime format
data['date']  = pd.to_datetime(data['date'],dayfirst=True)

In [ ]:
data.info()

* We observe that the date column has been converted to datetime format

In [ ]:
data.head()

**The column 'date' is now in datetime format. Now we can change the format of the date to any other format**

In [ ]:
data['date'].dt.strftime('%m/%d/%Y')

In [ ]:
data['date'].dt.strftime('%m-%d-%y')

**Extracting year from the date column**

In [ ]:
data['date'].dt.year

Creating a new column and adding the extracted year values into the dataframe.

In [ ]:
data['year'] = data['date'].dt.year

**Extracting month from the date column**

In [ ]:
data['date'].dt.month

Creating a new column and adding the extracted month values into the dataframe.

In [ ]:
data['month'] = data['date'].dt.month

**Extracting day from the date column**

In [ ]:
data['date'].dt.day

Creating a new column and adding the extracted day values into the dataframe.

In [ ]:
data['day'] = data['date'].dt.day

In [ ]:
data.head()

* We can see that year, month, and day columns have been added in the dataset.

In [ ]:
# The datetime format is convenient for many tasks!
data['date'][1]-data['date'][0]

In [ ]:
import numpy as np
np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [ ]:
np.arange(start=1, stop=10, step=1).reshape(3,3)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
array_1 = np.linspace(0,20,6)
array_2 = np.arange(0,20,6)
print(len(array_1))
print(len(array_2))

6
4


In [ ]:
mat = np.matrix([[ 1, 4, 9, 121, 144, 169],
                [ 16, 25, 36, 196, 225, 256],
                [ 49, 64, 81, 289, 324, 361]]).mean()


In [ ]:
mat

131.66666666666666

In [ ]:
a = np.arange(0,20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:

a[2:7]

array([2, 3, 4, 5, 6])

In [ ]:
np.cos([0, 1, 2, 3, 4])

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [ ]:
list_1 = [1,2,3]
list_2 = [4,5,6]
new_list = list_1 + list_2
new_list

[1, 2, 3, 4, 5, 6]

In [ ]:
array_1 = np.array([1,2,3])
array_2 = np.array([4,5,6])
new_array = array_1 + array_2
new_array

array([5, 7, 9])

In [ ]:
mat = np.array([[1, 2, 1], [4, 5, 9],[1, 8, 9]])
mat[1] = 5

In [ ]:
mat

array([[1, 2, 1],
       [5, 5, 5],
       [1, 8, 9]])

In [ ]:
array_1 = np.array([1, 2, 3, 5, 8])
array_2 = np.array([0, 3, 4, 2, 1])
new_array = array_1+ array_2
print(new_array)
final_array = new_array*array_1
print(final_array)
print(final_array[2])

[1 5 7 7 9]
[ 1 10 21 35 72]
21


In [ ]:
np.ones([2, 2])

array([[1., 1.],
       [1., 1.]])

In [ ]:
n1 = np.matrix([[121, 144, 169], [196, 225, 256], [ 289, 324, 361]])
n2 = np.matrix([[ 1, 4, 9], [ 1, 5, 4], [ 9, 4, 8]])
print(n1)
print(n2)
n1.dot(n2)

[[121 144 169]
 [196 225 256]
 [289 324 361]]
[[1 4 9]
 [1 5 4]
 [9 4 8]]


matrix([[1786, 1880, 3017],
        [2725, 2933, 4712],
        [3862, 4220, 6785]])

In [ ]:
import pandas as pd
data=pd.read_csv('/content/drive/MyDrive/Python Course/books.csv')
data.shape

(5000, 10)

In [ ]:
data.describe()

average_rating        isbn13    num_pages  ratings_count  \
count     5000.000000  5.000000e+03  4967.000000   5.000000e+03   
mean         3.931932  9.752758e+12   341.094021   2.017549e+04   
std          0.348741  5.129254e+11   230.986115   1.175026e+05   
min          0.000000  8.987060e+09     1.000000   0.000000e+00   
25%          3.770000  9.780345e+12   200.000000   1.050000e+02   
50%          3.960000  9.780571e+12   304.000000   7.915000e+02   
75%          4.140000  9.780871e+12   416.500000   5.348750e+03   
max          5.000000  9.789879e+12  3342.000000   2.457092e+06   

       text_reviews_count         year  
count         5000.000000  5000.000000  
mean           592.688600  2000.131800  
std           2539.539004     8.069043  
min              0.000000  1913.000000  
25%              9.000000  1998.000000  
50%             49.000000  2003.000000  
75%            249.000000  2005.000000  
max          55843.000000  2019.000000

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   title               5000 non-null   object 
 1   author              5000 non-null   object 
 2   average_rating      5000 non-null   float64
 3   isbn13              5000 non-null   int64  
 4   language_code       4923 non-null   object 
 5   num_pages           4967 non-null   float64
 6   ratings_count       5000 non-null   int64  
 7   text_reviews_count  5000 non-null   int64  
 8   publisher           5000 non-null   object 
 9   year                5000 non-null   int64  
dtypes: float64(2), int64(4), object(4)
memory usage: 390.8+ KB


In [ ]:
data['average_rating']>4

0       False
1        True
2       False
3       False
4        True
        ...  
4995     True
4996    False
4997    False
4998    False
4999     True
Name: average_rating, Length: 5000, dtype: bool

In [ ]:
data[data['average_rating']>4]

title  \
1     La Cucina Di Lidia: Recipes and Memories from ...   
4     The Killing Dance (Anita Blake  Vampire Hunter...   
5          The Hand of Chaos (The Death Gate Cycle  #5)   
6                                       On Intelligence   
11                        Merlin's Tour of the Universe   
...                                                 ...   
4991                                       'Salem's Lot   
4992                  A Mad People's History of Madness   
4993     A Christmas Carol (Great Illustrated Classics)   
4995                                 The Complete Works   
4999  The Avignon Quintet: Monsieur  Livia  Constanc...   

                           author  average_rating         isbn13  \
1     Lidia Matticchio Bastianich            4.14  9780767914222   
4             Laurell K. Hamilton            4.13  9780425209066   
5                   Margaret Weis            4.06  9780553563696   
6                    Jeff Hawkins            4.12  9780805078534   
11            Neil deGrasse Tyson            4.02  9780385488358   
...                           ...             ...            ...   
4991                 Stephen King            4.02  9780965772419   
4992                Dale Peterson            4.33  9780822953319   
4993             Malvina G. Vogel            4.36  9781596792371   
4995          Michel de Montaigne            4.44  9781400040216   
4999             Lawrence Durrell            4.07  9780571225552   

     language_code  num_pages  ratings_count  text_reviews_count  \
1            en-GB      288.0             48                   3   
4            en-US      368.0          59524                 946   
5              eng      446.0          16301                 117   
6              eng      261.0           5347                 396   
11             eng      318.0            305                  27   
...            ...        ...            ...                 ...   
4991           eng      405.0           1039                 130   
4992           eng      384.0              9                   0   
4993           eng      238.0            466                  31   
4995           eng     1392.0            166                  13   
4999         en-US     1376.0            287                  23   

                           publisher  year  
1                    Clarkson Potter  2003  
4                  Berkley Hardcover  2006  
5                            Spectra  1993  
6               St. Martin's Griffin  2005  
11                 Main Street Books  1997  
...                              ...   ...  
4991                       Doubleday  1975  
4992  University of Pittsburgh Press  1982  
4993         Abdo Publishing Company  2005  
4995              Everyman's Library  2003  
4999                   Faber & Faber  2004  

[2115 rows x 10 columns]

In [ ]:
data[(data['average_rating']>4.5) & (data['ratings_count']<10)]

title  \
63                                             鋼之鍊金術師 9   
178                                            鋼之鍊金術師 6   
224                             Stargirl LitPlans on CD   
454   Literature Circle Guide: Bridge to Terabithia:...   
584                       Falling Angels (Luc Actar #1)   
681        Fanning the Flame: Bible  Cross  and Mission   
696                  Tyrannosaurus Wrecks (Stanley  #1)   
741   The John Deere Two-Cylinder Tractor Encycloped...   
757   The American Campaign: U.S. Presidential Campa...   
1837  The Goon Show  Volume 4: My Knees Have Fallen ...   
1856                                          鋼之鍊金術師 10   
1960  Wissenschaft der Logik: Die Lehre Vom Begriff ...   
2244  Getting a Grip on the Basics: Building a Firm ...   
2496                               Come Away My Beloved   
3178  Organizational Architecture: Designs for Chang...   
3438         Bill Gates: Computer Legend (Famous Lives)   
3706  A Wife After God's Own Heart Growth and Study ...   
3833  His Princess Devotional: A Royal Encounter Wit...   
3909                 Little Big Book for God's Children   
3927  Colossians and Philemon: A Critical and Exeget...   
4108                  Willem de Kooning: Late Paintings   
4415                                           Corvette   
4455  The Complete Theory Fun Factory: Music Theory ...   
4917                          Taxation of Mineral Rents   
4933  Oliver Wendell Holmes in Paris: Medicine  Theo...   

                             author  average_rating         isbn13  \
63                   Hiromu Arakawa            4.57  9789861156521   
178                  Hiromu Arakawa            4.58  9789861146140   
224                 Mary B. Collins            4.86  9781583372920   
454                  Tara MacCarthy            5.00  9780439271714   
584               Melissa M. Garcia            4.67  9780595377107   
681                  Chris    Green            5.00  9780310249870   
696                  Laura Driscoll            5.00  9780786845033   
741                   Don Macmillan            4.75  9780760329634   
757               James E. Campbell            5.00  9780890969403   
1837                     NOT A BOOK            5.00  9780563388692   
1856                 Hiromu Arakawa            4.60  9789861156538   
1960  Georg Wilhelm Friedrich Hegel            4.78  9783787307678   
2244                  Beth A. Jones            4.67  9781577948261   
2496             Frances J. Roberts            4.58  9781593109158   
3178                David A. Nadler            4.62  9781555424435   
3438               Sara Barton-Wood            5.00  9780739844328   
3706               Elizabeth George            4.69  9780736911689   
3833            Sheri Rose Shepherd            5.00  9781590529621   
3909                     Alice Wong            4.88  9780941807555   
3927                 R. McL. Wilson            5.00  9780567044716   
4108                Julie Sylvester            5.00  9783829602266   
4415                   Jerry Burton            4.83  9780883631218   
4455              Ian        Martin            5.00  9780851621814   
4917                   Ross Garnaut            5.00  9780198284543   
4933             William C. Dowling            5.00  9781584655800   

     language_code  num_pages  ratings_count  text_reviews_count  \
63             NaN      184.0              4                   0   
178            NaN      191.0              5                   0   
224            eng      210.0              5                   0   
454            eng       32.0              4                   1   
584            eng      216.0              1                   0   
681            eng      336.0              1                   1   
696            eng       24.0              2                   1   
741            eng      256.0              4                   0   
757            eng      314.0              0                   0   
1837          

In [ ]:
# What is the mean of ‘average_rating’ for the books where ‘language_code’ is ‘eng’?
data[data['language_code']=='eng']['average_rating'].mean()


3.931142857142857

In [ ]:
data.loc[[1, 5],['language_code', 'num_pages', 'ratings_count']]

language_code  num_pages  ratings_count
1         en-GB      288.0             48
5           eng      446.0          16301

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   title               5000 non-null   object 
 1   author              5000 non-null   object 
 2   average_rating      5000 non-null   float64
 3   isbn13              5000 non-null   int64  
 4   language_code       4923 non-null   object 
 5   num_pages           4967 non-null   float64
 6   ratings_count       5000 non-null   int64  
 7   text_reviews_count  5000 non-null   int64  
 8   publisher           5000 non-null   object 
 9   year                5000 non-null   int64  
dtypes: float64(2), int64(4), object(4)
memory usage: 390.8+ KB


In [ ]:
data['num_pages'].describe()

count    4967.000000
mean      341.094021
std       230.986115
min         1.000000
25%       200.000000
50%       304.000000
75%       416.500000
max      3342.000000
Name: num_pages, dtype: float64

In [ ]:
# How many books were published in 2010?
data[data['year']==2010].count()

title                 15
author                15
average_rating        15
isbn13                15
language_code         15
num_pages             15
ratings_count         15
text_reviews_count    15
publisher             15
year                  15
dtype: int64

In [ ]:
data[(data['publisher']=='DAW') & (data['average_rating']>4)]['author'].unique()

array(['Mercedes Lackey', 'Sharon Green'], dtype=object)

In [ ]:
data[(data['num_pages']>500) & (data['year']>2010)]['title'].count()

5

In [ ]:
data[data['author']=='Agatha Christie']['title'].count()


21

In [ ]:
data[(data['language_code']=='spa') & (data['year']>2000)]['title'].count()

84

In [ ]:
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))
demo_matrix[0:3, 1:3]


array([[35, 74],
       [37, 37],
       [39, 93]])

In [ ]:
import numpy as np
demo_array = np.arange(0,10)
demo_array<3

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [ ]:
flowers = pd.Series([2, 3, 5, 4], index=['lily', 'rose', 'daisy', 'lotus'])
flowers['daisy']

lily     2
rose     3
daisy    5
lotus    4
dtype: int64

In [ ]:
# Consider the following dataframe named “data_customer” -

#customer	category	important	sales
#0	101	cat2	yes 	123
#1	102	cat2	no 	52
#2	103	cat1	yes 	214
#3	104	cat3	yes	663
data_customer={'customer':[0,1,2,3], 'category':['cat2','cat2','cat1','cat3'],'important':['yes','no','yes','yes'],'sales':[123,52,214,663]}

# find the number of customers in each of the categories?
data_customer = pd.DataFrame(data_customer)
data_customer.groupby(['category'])['customer'].count()




category
cat1    1
cat2    2
cat3    1
Name: customer, dtype: int64

In [ ]:
data_customer.sort_values(by='sales',ascending=False)

customer category important  sales
3         3     cat3       yes    663
2         2     cat1       yes    214
0         0     cat2       yes    123
1         1     cat2        no     52

In [ ]:
data_customer.loc[[1,2], ['customer', 'sales']]


customer  sales
1         1     52
2         2    214

In [ ]:
data_customer.groupby(['customer'])['sales'].mean()

customer
0    123.0
1     52.0
2    214.0
3    663.0
Name: sales, dtype: float64